root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/echo-server ."
  bin = "./tmp/echo-server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test.go"]
  delay = 500
  stop_on_error = true
  log = "tmp/build-errors.log"

[misc]
  clean_on_exit = true
